name: Deploy FastAPI via Docker

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      # 코드 체크아웃
      - name: Checkout repository
        uses: actions/checkout@v3

      # 환경파일 생성 (.env)
      - name: Create .env file
        run: echo "MYSQL_USER=root
MYSQL_PASSWORD=eddi@123
MYSQL_HOST=localhost
MYSQL_PORT=3306
MYSQL_DATABASE=multi_agent_db

POSTGRES_USER=eddi
POSTGRES_PASSWORD=eddi@123
POSTGRES_HOST=localhost
POSTGRES_PORT=5432
POSTGRES_DB=vectordb

APP_POSTGRES_USER=eddi
APP_POSTGRES_PASSWORD=eddi@123
APP_POSTGRES_HOST=localhost
APP_POSTGRES_PORT=5432
APP_POSTGRES_DB=appdb

ANTHROPIC_API_KEY=여기에_Anthropic_API_키_입력

AUTH_PASSWORD=0
JWT_SECRET_KEY=0


SERP_API_KEY=6be021a711033bee6024a1c03baed70a092af7ed6eb40f012fea5616aeabb0e0
OPENAI_API_KEY=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

KAKAO_CLIENT_ID=bcdffa8f5827104be86b973a8d9ab639
KAKAO_REDIRECT_URI=http://localhost:33333/api/v1/kakao-authentication/request-access-token-after-redirection

REDIS_PASSWORD=eddi@123

CORS_ALLOWED_FRONTEND_URL=http://localhost:3000

YOUTUBE_API_KEY=AIzaSyALHzJ1pIhLtuSLr4oKbWwPPf9IKc6915w

OPEN_DART_API_KEY=332eed3fece43abcb425fc05f1953680185da6eb
NAVER_CLIENT_ID=UToRKaFsnNitSuVaHqP3
NAVER_CLIENT_SECRET=C1r5xHfrTo" > .env

      # QEMU 설정 (멀티 아키텍처)
      - uses: docker/setup-qemu-action@v2

      # Buildx 설정
      - uses: docker/setup-buildx-action@v2

      # GHCR 로그인
      - name: Log in to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: minstabb
          password: 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

      # Docker 이미지 빌드 & 푸시
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ghcr.io/minstabb/fastapi-app:latest
          platforms: linux/amd64,linux/arm64

  deploy:
    needs: build-and-push
    runs-on: [self-hosted, fastapi-server]

    steps:
      # GHCR 로그인
      - name: GHCR Login
        run: echo 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 | docker login ghcr.io -u minstabb --password-stdin

      # 최신 이미지 pull
      - name: Pull latest image
        run: docker pull ghcr.io/minstabb/fastapi-app:latest

      # 기존 컨테이너 중지 및 정리
      - name: Stop old container
        run: |
          docker-compose down
          docker image prune -f
          docker logout

      # Docker Compose로 FastAPI + MySQL + Redis 실행
      - name: Run containers
        run: docker-compose up -d --build
